### ISSUE TITLE
Elaplacenet5 ,gdatasave文件夹找不到 

### ISSUE THREAD

**Issue by kangxin8** [liguge/EWSNet#2]
作者您好，请问Elaplacenet5 ,gdatasave这两个文件在哪里呀，我没有找到

**Comment by liguge** [comment]
即插即用的框架，放入自己的模型即可，不需要model和data载入文件。



在 2024-01-11 15:50:35，"kangxin8" ***@***.***> 写道：

作者您好，请问Elaplacenet5 ,gdatasave这两个文件在哪里呀，我没有找到

**Comment by kangxin8** [comment]
好的，谢谢啦
